# mkdocs.yml
site_name: barto14753
site_url: https://barto14753.github.io/blog
site_author: Bartosz Włodarski
site_description: A blog about technology and programming

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - blog:
      blog_dir: .
      post_dir: "{blog}/posts"
      categories: true
  - search
  - tags

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - meta
  - tables
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home:
      - index.md
      - posts/2024-01-16-totp.md
      - posts/2024-04-01-react-on-github-pages.md
      - posts/2024-07-17-hydra-walkthrough.md
      - posts/2024-11-25-simple-development-environment-for-python.md
  - About: about.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/barto14753
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/bartosz-w%C5%82odarski-a549b9208/

extra_css:
  - assets/stylesheets/custom.css
